version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      MONGO_URI: mongodb://mongo:27017/tasks
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27027:27017

